[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py
python_classes = *Tests
python_functions = test_*
addopts =
    --cov=author
    --cov=core
    --cov-report=term-missing
    --cov-report=xml:coverage.xml
    -p no:warnings
    --tb=short
