"""API v1 URL configuration — mirrors /api/ under /api/v1/"""
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from author.views import (
    RegisterView, ProfileView, PublicPostListView, PublicProfilePostsView,
    TagListCreateView, PostTagView, BookmarkView, BookmarkListView,
    FollowView, UnfollowView, UserPublicProfileView,
    PostCommentListCreateView, CommentDetailView,
    PostReactView, CommentReactView, NotificationListView,
    CitationListCreateView, CitationDetailView, EvidencePanelView,
    PostChangelogView, PostReviewListCreateView,
    ReportPostView, ReportCommentView, HideCommentView,
    SeriesListCreateView, SeriesDetailView, SeriesPostView,
    BlockView, PostPinView, TrendingPostsView, PostViewCountView,
    CoAuthorView, OpenGraphView, UserStatsView, SubscribeView, SubscriptionListView,
    DataExportView, HealthCheckView, AccountDeleteView,
    MarkNotificationsReadView, MeView,
)

urlpatterns = [
    path('schema/', SpectacularAPIView.as_view(), name='v1-schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='v1-schema'), name='v1-swagger-ui'),
    path('token/', TokenObtainPairView.as_view(), name='v1-token'),
    path('token/refresh/', TokenRefreshView.as_view(), name='v1-token-refresh'),
    path('auth/register/', RegisterView.as_view(), name='v1-register'),
    path('auth/profile/', ProfileView.as_view(), name='v1-profile'),
    path('public/posts/trending/', TrendingPostsView.as_view(), name='v1-trending-posts'),
    path('public/posts/', PublicPostListView.as_view(), name='v1-public-post-list'),
    path('public/posts/<slug:slug>/og/', OpenGraphView.as_view(), name='v1-post-og'),
    path('public/profiles/<str:handle>/posts/', PublicProfilePostsView.as_view(), name='v1-public-profile-posts'),
    path('tags/', TagListCreateView.as_view(), name='v1-tag-list'),
    path('posts/<int:post_id>/tags/', PostTagView.as_view(), name='v1-post-tag-add'),
    path('posts/<int:post_id>/tags/<int:tag_id>/', PostTagView.as_view(), name='v1-post-tag-remove'),
    path('posts/<int:pk>/bookmark/', BookmarkView.as_view(), name='v1-bookmark'),
    path('bookmarks/', BookmarkListView.as_view(), name='v1-bookmark-list'),
    path('users/<int:pk>/', UserPublicProfileView.as_view(), name='v1-profile-detail'),
    path('users/<int:pk>/follow/', FollowView.as_view(), name='v1-follow'),
    path('users/<int:pk>/unfollow/', UnfollowView.as_view(), name='v1-unfollow'),
    path('users/<int:pk>/block/', BlockView.as_view(), name='v1-block'),
    path('users/<int:pk>/stats/', UserStatsView.as_view(), name='v1-user-stats'),
    path('users/<int:pk>/subscribe/', SubscribeView.as_view(), name='v1-subscribe'),
    path('subscriptions/', SubscriptionListView.as_view(), name='v1-subscription-list'),
    path('posts/<int:post_id>/comments/', PostCommentListCreateView.as_view(), name='v1-post-comments'),
    path('comments/<int:pk>/', CommentDetailView.as_view(), name='v1-comment-detail'),
    path('posts/<int:pk>/react/', PostReactView.as_view(), name='v1-post-react'),
    path('comments/<int:pk>/react/', CommentReactView.as_view(), name='v1-comment-react'),
    path('notifications/', NotificationListView.as_view(), name='v1-notifications'),
    path('posts/<int:post_id>/citations/', CitationListCreateView.as_view(), name='v1-post-citations'),
    path('citations/<int:pk>/', CitationDetailView.as_view(), name='v1-citation-detail'),
    path('posts/<int:pk>/evidence/', EvidencePanelView.as_view(), name='v1-post-evidence'),
    path('posts/<int:pk>/changelog/', PostChangelogView.as_view(), name='v1-post-changelog'),
    path('posts/<int:post_id>/reviews/', PostReviewListCreateView.as_view(), name='v1-post-reviews'),
    path('posts/<int:pk>/report/', ReportPostView.as_view(), name='v1-report-post'),
    path('comments/<int:pk>/report/', ReportCommentView.as_view(), name='v1-report-comment'),
    path('comments/<int:pk>/hide/', HideCommentView.as_view(), name='v1-hide-comment'),
    path('series/', SeriesListCreateView.as_view(), name='v1-series-list'),
    path('series/<int:pk>/', SeriesDetailView.as_view(), name='v1-series-detail'),
    path('series/<int:series_id>/posts/', SeriesPostView.as_view(), name='v1-series-posts'),
    path('posts/<int:pk>/pin/', PostPinView.as_view(), name='v1-post-pin'),
    path('posts/<int:pk>/view/', PostViewCountView.as_view(), name='v1-post-view'),
    path('posts/<int:pk>/co-authors/', CoAuthorView.as_view(), name='v1-co-authors'),
    path('auth/export/', DataExportView.as_view(), name='v1-data-export'),
    path('auth/account/', AccountDeleteView.as_view(), name='v1-account-delete'),
    path('auth/me/', MeView.as_view(), name='v1-me'),
    path('notifications/mark-read/', MarkNotificationsReadView.as_view(), name='v1-notifications-mark-read'),
    path('health/', HealthCheckView.as_view(), name='v1-health'),
    path('', include('author.urls')),
]
